### ISSUE TITLE
[问题] 请问文章右侧的 toc widget 是怎么实现的呢？

### ISSUE THREAD

**Issue by qiwihui** [selfboot/selfboot.github.io#1]
比如：

![image](https://cloud.githubusercontent.com/assets/3297411/22957140/5c435fdc-f361-11e6-846a-ca37c8d11de6.png)

在你 fork 的 maupassant theme 中没有发现相关代码实现，求指点。

**Comment by selfboot** [comment]
这里是我自己加的部分。你可以参考 https://github.com/selfboot/maupassant-hexo 我 fork 出来的主题
